### ISSUE TITLE
Error while uploading file

### ISSUE THREAD

**Issue by Dhruv80576** [manjit-hub/Notorite#30]
Error while uploading documents. authorization error while calling api due to not passing token.
![image](https://github.com/user-attachments/assets/63986ce8-b97b-49e6-98d6-eed2bf147e48)
![image](https://github.com/user-attachments/assets/f57bda35-7975-44af-a145-383faded814c)

**Comment by Bluesparx** [comment]
Yes, we need to work on Notes controllers and routes in backend. Please assign it to me @manjit-hub

**Comment by Dhruv80576** [comment]
@manjit-hub 
I have already resolved issues related to api just need to work on storing notes.
Can u assign it to me

**Comment by mjkoder** [comment]
@Dhruv80576 as you have resolved api issue. Please proceed with storing notes part.

**Comment by mjkoder** [comment]
@Bluesparx can you also look into it ?? Such that files should be uploaded to server and stored there.

**Comment by Bluesparx** [comment]
Hi, great work Dhruv! 
@manjit-hub this is part of frontend so we don't directly need to use cloudinary instead we'll put up some API request handler which isn't set up yet so it's fine for now.  In my previous PR I have only resolved sign up image upload. We need to work on Note uploader controller. Can I open a new PR since it is totally unrelated to this.

**Comment by mjkoder** [comment]
@Bluesparx yes, I have no idea about it. I'm closing this for the moment.

**Comment by Bluesparx** [comment]
It's okay, although the pr looks good to me u can merge that without the backend funtionality too.
