### ISSUE TITLE
Fix Note Routes and Controller

### ISSUE THREAD

**Issue by Bluesparx** [manjit-hub/Notorite#44]
Implement the following:
1. Remove use of disk storage in notes router.
2. Use middleware for image upload in notes controller.

**Comment by mjkoder** [comment]
Same here explain how you will ressolve these. What outcome we will get ?

**Comment by Shivansh-0403** [comment]
@manjit-hub there were some issues in notes controller because the JWT token was not getting authenticated properly and the file was not getting uploaded. So, I have worked on that issue. Also slight enhancement to display the name of the creater of a note on searching for notes.
And, one doubt, do you want to upload the document coming from uploadNote API on cloudinary or simply in the disk storage using multer, because the current codebase of your repo doesn't upload the note on cloudinary. So, I can add that as well.

**Comment by mjkoder** [comment]
@Shivansh-0403 go for it. And make uplod to Cloudinary.
