### ISSUE TITLE
bug: On refreshing login page is presented

### ISSUE THREAD

**Issue by Satvik1769** [manjit-hub/Notorite#72]
This shouldn't happen token should be saved in local storage for sometime such that user doesn't have to login again and again

**Comment by mjkoder** [comment]
can you fix this ? @Satvik1769

**Comment by mjkoder** [comment]
@Satvik1769 This is happening for entire routes. Please fix it.

**Comment by Satvik1769** [comment]
Hi what issue are you referring can you explain in detail

**Comment by mjkoder** [comment]
@Satvik1769 Basically whenever user is successfully logged in, the user token is not stored anywhere (expected to be handled by Redux or store in local storage). Due to which whenver user try to refresh the website, he/she gets log out. So user have to log in again. 

So basically we have to store that success token somewhere and provide it to entire application. Generally we use userContext to provide Authentiction throughout the sit.

**Comment by Satvik1769** [comment]
[Screencast from 20-10-24 03:00:56 PM IST.webm](https://github.com/user-attachments/assets/bf803ca5-f18e-46d8-b961-51c0b69e5d96)

**Comment by Nihal-devTech** [comment]
I hve seen this issue and I was thinking about the approach as-
1. we can manage the authentication globally using context API
2. we can create a private route component that will check the token and ensure that protected routes are only accessible if the user is authenticated.

**Comment by Satvik1769** [comment]
We can do with your way too, however I have already created pull request for this issue # 75

It also has protected route as you said and instead of using useContext we are using localstorage to store and get token

**Comment by mjkoder** [comment]
https://github.com/user-attachments/assets/df492232-f439-4505-a24f-38eec68d5f99

Look into this issue. On refreshing it giving this '404 NOT FOUND' error. 
1. 'client' is deployed in Vercel
2. 'server' is on Render

I got some info that issue is related to Vercel but not have clear id
ea how to resolve. If you can do it then do it. @Satvik1769 @Nihal-devTech

**Comment by Satvik1769** [comment]
move vercel.json file in client folder and then it will work

**Comment by mjkoder** [comment]
@Satvik1769 great it's working fine now.
